Repository frequenz-floss/frequenz-api-weather, pull requests merged in 2024-01, with the labels that each got.

#61 Add wind 10m uv component features to proto specs
  RELEASE_NOTES.md
  proto/frequenz/api/weather/weather.proto
Labels: part:docs

#73 Run linters on the client code
  noxfile.py
  pyproject.toml
Labels: part:tooling

#70 Fix nox issues
  noxfile.py
  py/frequenz/client/weather/__init__.py
  py/frequenz/client/weather/_client.py
  py/frequenz/client/weather/_types.py
  pyproject.toml
Labels: part:tooling, cmd:skip-release-notes

#75 Fix doc for 2m temperature in proto specs
  proto/frequenz/api/weather/weather.proto
Labels: cmd:skip-release-notes

#74 Add client support 10m wind and temperature features
  RELEASE_NOTES.md
  py/frequenz/client/weather/_types.py
Labels: part:docs

#76 Clean up RELEASE_NOTES.md for release
  RELEASE_NOTES.md
Labels: part:docs
