Repository frequenz-floss/frequenz-api-weather, pull requests merged in 2025-02, with the labels that each got.

#150 Clear release notes
  RELEASE_NOTES.md
Labels: part:docs

#146 Update repo-config to v0.10.0
  .github/containers/test-installation/Dockerfile
  .github/workflows/ci.yaml
  .github/workflows/release-notes-check.yml
  docs/_scripts/macros.py
  mkdocs.yml
  pyproject.toml
Labels: part:docs, part:tooling

#151 Fix CI
  .github/workflows/ci.yaml
  pyproject.toml
Labels: part:tooling
